export const LOAD_EXPENSE_TYPES_SUCCESS = 'LOAD_EXPENSE_TYPES_SUCCESS';
export const CREATE_EXPENSE_TYPE_SUCCESS = 'CREATE_EXPENSE_TYPE_SUCCESS';
export const UPDATE_EXPENSE_TYPE_SUCCESS = 'UPDATE_EXPENSE_TYPE_SUCCESS';
export const DELETE_EXPENSE_TYPE_SUCCESS = 'DELETE_EXPENSE_TYPE_SUCCESS';

export const LOAD_EXPENSE_MASTERS_SUCCESS = 'LOAD_EXPENSE_MASTERS_SUCCESS';
export const CREATE_EXPENSE_MASTER_SUCCESS = 'CREATE_EXPENSE_MASTER_SUCCESS';
export const UPDATE_EXPENSE_MASTER_SUCCESS = 'UPDATE_EXPENSE_MASTER_SUCCESS';
export const DELETE_EXPENSE_MASTER_SUCCESS = 'DELETE_EXPENSE_MASTER_SUCCESS';